# Under no circumstances will this prohibit players
# from creating banners that are normal in vanilla
#
#
# Permission usage:
#   betterbanner.basic        - make up to 'basic' layers
#   betterbanner.intermediate - make up to 'intermediate' layers
#   betterbanner.advanced     - make up to 'advancded' layers
#   betterbanner.unlimited    - what it says
#
#
# Commands:
#   /betterbanner reload      - reloads the config
#   /betterbanner debug       - crap ton msgs in server log
#   /betterbanner ver         - shows version number
#
#
# copying of deep banners.
#   none = no copying of 7+ layer banners, keeps them special
#   perm = can copy banners up to their permission to create
#   all  = everyone can copy all banners
#
copy: none
#
#
# layer limits for perms. Can not stop vanilla crafting.
#
default: 6
basic: 8
intermediate: 11
advanced: 15
