name: BetterBanner
main: com.netrust.betterbanner.BetterBanner
version: 0.1.7
authors: [jootunk, sarhatabaot]
api-version: 1.13
commands:
  betterbanner:
    usage: /<command> <reload|debug|version>
    description: BetterBanner
    